[package]
name = "felt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "*"
num-bigint = { version = "0.4", features = ["serde"], optional = true }
num-traits = "*"
lazy_static = "*"
serde = { version = "1.0", features = ["derive"] }
ibig = { version = "0.3.6", features = ["serde"], optional = true }

[features]
ibig-felt = ["ibig"]
bigint-felt = ["num-bigint"]
